name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx prisma generate"
dev = "node ./scripts/prisma-db-push-safe.mjs && npm exec react-router dev"
